[package]
name = "salsa"
version = "0.12.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/salsa-rs/salsa"
description = "A generic framework for on-demand, incrementalized computation (experimental)"
readme = "README.md"

[dependencies]
derive-new = "0.5.5"
rustc-hash = "1.0"
parking_lot = "0.7.0"
lock_api = "0.1.4"
indexmap = "1.0.1"
log = "0.4.5"
smallvec = "0.6.5"
salsa-macros = { version = "0.12.0", path = "components/salsa-macros" }

[dev-dependencies]
diff = "0.1.0"
env_logger = "0.5.13"
rand = "0.5.5"

[workspace]
